In [77]:
from sklearn.cluster import KMeans
import numpy as np
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.cluster import SpectralClustering
import seaborn as sns; sns.set()  # for plot styling
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report



In [59]:
print('Loading data ...')
# train = pd.read_csv('FeatureVect.csv')
train = pd.read_csv('output.csv')

print('Creating training set ...')
x_train = train.drop(['LABEL'], axis=1)
y_train = train['LABEL'].values
print(x_train.shape, y_train.shape)


Loading data ...
Creating training set ...
(500, 17) (500,)


In [60]:
print(x_train.shape, y_train.shape)
print(x_valid.shape, y_valid.shape)

(500, 17) (500,)
(100, 17) (100,)


In [78]:
kmeans = KMeans(n_clusters=4)
X= x_train

kmeans.fit(X)
y_kmeans = kmeans.predict(X)
print( confusion_matrix(y_train, y_kmeans))
print( classification_report(y_train, y_kmeans))


[[  0   0   0   2]
 [ 19  29  15  13]
 [ 93 110  85  74]
 [ 13  14  18  15]]
             precision    recall  f1-score   support

          0       0.00      0.00      0.00         2
          1       0.19      0.38      0.25        76
          2       0.72      0.23      0.35       362
          3       0.14      0.25      0.18        60

avg / total       0.57      0.26      0.32       500



In [62]:
# plt.scatter(x_train[:], x_train[:], c=y_kmeans, s=50, cmap='viridis')
# centers = kmeans.cluster_centers_
# plt.scatter(centers[:, 0], centers[:, 1], c='black', s=200, alpha=0.5);

In [63]:
model = SpectralClustering(n_clusters=4, affinity='nearest_neighbors',
                           assign_labels='kmeans')
labels = model.fit_predict(X)

In [64]:
# for i in range(len(y_kmeans)):
#     print (y_train[i],  labels[i])

In [76]:
print( confusion_matrix(y_train, labels))


[[  0   1   1   0]
 [ 23  13  35   5]
 [100  86 135  41]
 [ 13  19  21   7]]


In [72]:

max_accu= len(x_train)
accuracy=max_accu
for i in range(len(x_train)):
    if abs(y_train[i] - labels[i]) >=2 :
        accuracy -=1

print (accuracy)
accuracy = accuracy / max_accu *100

print (accuracy)

362
72.39999999999999
